#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
#cp -r /app/staticfiles/admin /app/elopub/static/admin
exec /usr/local/bin/gunicorn elopub.wsgi --bind 0.0.0.0:5000 --chdir=/app
